# Generated by Django 3.0.8 on 2022-12-15 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20221215_1957'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='autor',
            new_name='author',
        ),
        migrations.RenameField(
            model_name='task',
            old_name='finished',
            new_name='important',
        ),
        migrations.AddField(
            model_name='task',
            name='deadline',
            field=models.DateTimeField(null=True),
        ),
    ]
