# Generated by Django 3.0.8 on 2022-12-15 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_remove_task_important'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='finished',
            field=models.BooleanField(default=False, verbose_name='finished'),
        ),
    ]
